#!/usr/bin/env bash
# Disable reverse-path filtering on the interfaces LNet is configured
# to use, and persist that as a sysctl drop-in.
#
# Why this is needed:
#
# rc.local puts every extra NIC (--nic) on the *same* /24 as the mgmt
# NIC -- there's one subnet and one default route, no source-based
# routing from the OS side.  With two or more interfaces on a shared
# subnet, a reply can legitimately arrive on an interface that isn't
# the one the kernel's reverse-path lookup would pick for that source
# address.  Under the RHEL/Rocky default of rp_filter=1 (strict, per
# RFC 3704) the kernel silently drops those packets.
#
# The failure mode is nasty precisely because it is silent: LNet peers
# discover each other, `lctl ping` may even work over one rail, and
# then bulk traffic stalls until the RPC times out.  It reads as a
# Lustre bug rather than a host networking setting.
#
# ksocklnd does install its own MR routes by default
# (skip_mr_route_setup=0), which helps traffic leave via the right
# interface -- but it does not change how the *receive* path is
# filtered.  rp_filter still has to be off.
#
# Note the kernel evaluates rp_filter as
#     max(conf.all.rp_filter, conf.<iface>.rp_filter)
# so clearing the per-interface knob alone is not enough -- 'all' has
# to be cleared too.  'default' is set so interfaces that appear later
# (softroce rxe links, hotplugged NICs) inherit 0.
#
# Usage:
#     setup-lnet-rp-filter.sh                      # /etc/modprobe.d/lnet.conf
#     setup-lnet-rp-filter.sh /path/to/lnet.conf
#     echo 'options lnet networks="tcp0(eth0)"' | \
#         setup-lnet-rp-filter.sh --stdin          # parse only, no writes
#
# Env:
#     SYSCTL_CONF_DIR    override for /etc/sysctl.d (tests)
#     PROC_NET_CONF      override for /proc/sys/net/ipv4/conf (tests)
#     APPLY              set to 'no' to skip the live `sysctl -w` pass

set -euo pipefail

PROG=$(basename "$0")

log() {
	printf '%s: %s\n' "$PROG" "$*" >&2
	if command -v logger >/dev/null 2>&1; then
		logger -t "$PROG" -- "$*" || true
	fi
}

lnet_ifaces() {
	# Read an lnet.conf body on stdin, print one interface name per
	# line in the order they appear.
	#
	# The emitter writes:
	#     options lnet networks="tcp0(eth0),o2ib0(eth1)"
	# so the names we want are exactly the parenthesised tokens.
	#
	# Entries that are not netdevs are deliberately included here and
	# filtered by the caller against PROC_NET_CONF -- that drops both
	# real ibdev names (mlx5_0, resolved from a 'passthrough' NIC) and
	# any '@ib-of-ethN' placeholder the resolver could not resolve.
	# rp_filter is an IPv4 routing knob and simply does not exist for
	# an IB device, so there is nothing to set in either case.
	sed -n 's/.*networks="\([^"]*\)".*/\1/p' |
		tr ',' '\n' |
		sed -n 's/.*(\([^)]*\)).*/\1/p'
}

main() {
	local conf=""
	local from_stdin=false

	while (($# > 0)); do
		case "$1" in
		--stdin)
			from_stdin=true
			shift
			;;
		-h | --help)
			sed -n '2,44p' "$0"
			return 0
			;;
		*)
			conf=$1
			shift
			;;
		esac
	done

	local body
	if [[ $from_stdin == true ]]; then
		body=$(cat)
		# Parse-only mode for tests: emit the interface list and stop.
		printf '%s\n' "$body" | lnet_ifaces
		return 0
	fi

	conf=${conf:-/etc/modprobe.d/lnet.conf}
	if [[ ! -s $conf ]]; then
		# No LNet config -- nothing is using multiple rails yet.  Quiet
		# exit; this is the normal case on a single-NIC VM before
		# deploy-lustre has run.
		return 0
	fi
	body=$(cat "$conf")

	local sysctl_dir=${SYSCTL_CONF_DIR:-/etc/sysctl.d}
	local proc_conf=${PROC_NET_CONF:-/proc/sys/net/ipv4/conf}
	local out=$sysctl_dir/99-lustre-lnet-rp-filter.conf

	# Keep only names that have an rp_filter knob (i.e. real netdevs).
	local -a ifaces=()
	local i
	while IFS= read -r i; do
		[[ -n $i ]] || continue
		if [[ -e $proc_conf/$i/rp_filter ]]; then
			ifaces+=("$i")
		fi
	done < <(printf '%s\n' "$body" | lnet_ifaces)

	mkdir -p "$sysctl_dir"
	{
		printf '# Generated by %s -- do not edit.\n' "$PROG"
		printf '# Lustre LNet needs rp_filter off on multi-homed\n'
		printf '# interfaces; see the script header for why.\n'
		printf 'net.ipv4.conf.all.rp_filter = 0\n'
		printf 'net.ipv4.conf.default.rp_filter = 0\n'
		for i in "${ifaces[@]:-}"; do
			[[ -n $i ]] || continue
			printf 'net.ipv4.conf.%s.rp_filter = 0\n' "$i"
		done
	} >"$out"

	# The drop-in alone only takes effect on the next boot (or a
	# `sysctl --system`), and rc.local runs after the interfaces are
	# already up -- so apply it live as well.
	if [[ ${APPLY:-yes} != no ]] && command -v sysctl >/dev/null 2>&1; then
		sysctl -q -w net.ipv4.conf.all.rp_filter=0 2>/dev/null || true
		sysctl -q -w net.ipv4.conf.default.rp_filter=0 2>/dev/null || true
		for i in "${ifaces[@]:-}"; do
			[[ -n $i ]] || continue
			sysctl -q -w "net.ipv4.conf.$i.rp_filter=0" 2>/dev/null || true
		done
	fi

	log "rp_filter disabled for [${ifaces[*]:-none} all default] via $out"
}

# Only invoke main when run as a script (not when sourced).
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
	main "$@"
fi
