"""Shell registration for ltvm's argcomplete-based tab completion.

The completers themselves live in :mod:`ltvm_pkg.completion`; this
module is only about getting a shell to *ask* ltvm for them.

Three shells, three conventions:

* **bash** sources every file in ``/etc/bash_completion.d`` at startup,
  so the argcomplete shellcode goes there verbatim.
* **zsh** autoloads ``_ltvm`` from a directory on ``fpath``.  An
  autoloaded file's body *is* the completion function, so the bare
  shellcode would define ``_python_argcomplete`` and return without
  completing anything -- the first TAB would come up empty and only the
  second would work.  :func:`shellcode` therefore wraps it in a
  ``#compdef`` header and a trailing call.
* **fish** reads ``complete`` directives from its completion dirs.

We generate all three with :func:`argcomplete.shellcode` in-process
rather than shelling out to ``register-python-argcomplete``, so the
install does not depend on that script being on PATH (it lives in the
venv's ``bin/``, which ``sudo ltvm install`` does not have).
"""

from __future__ import annotations

import logging
import os
import shutil
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger("ltvm.completion")

SHELLS = ("bash", "zsh", "fish")

# Prefix for every system path below.  Set it to stage completion into
# an image or chroot instead of the running host -- and the test suite
# sets it so that `ltvm doctor --fix` under pytest writes into a tmpdir
# rather than the developer's real /etc.  Read through a function, never
# captured at import: a fixture that sets it after this module is first
# imported must still take effect.
_ROOT_ENV = "LTVM_COMPLETION_ROOT"

# Where each shell picks completions up, in preference order.  The
# first existing directory wins; when none exists we fall back to
# creating the last entry, which is the sysadmin-owned location that a
# package upgrade will not overwrite.
_SEARCH: dict[str, tuple[str, ...]] = {
    "bash": (
        "/etc/bash_completion.d",
        "/usr/share/bash-completion/completions",
    ),
    "zsh": (
        "/usr/share/zsh/site-functions",
        "/usr/share/zsh/vendor-completions",
        "/usr/local/share/zsh/site-functions",
    ),
    "fish": (
        "/usr/share/fish/vendor_completions.d",
        "/etc/fish/completions",
    ),
}

# The filename each shell expects.  zsh's underscore prefix is not
# cosmetic: compinit only scans fpath entries matching ``_*``.
_FILENAME: dict[str, str] = {
    "bash": "ltvm",
    "zsh": "_ltvm",
    "fish": "ltvm.fish",
}


def shellcode(shell: str) -> str:
    """The registration script for *shell*.

    Raises ValueError for an unknown shell and ImportError when
    argcomplete is not installed (which ltvm depends on, so this only
    happens on a broken environment).
    """
    if shell not in SHELLS:
        raise ValueError(
            f"unknown shell {shell!r} (expected one of {', '.join(SHELLS)})"
        )
    import argcomplete

    code: str = argcomplete.shellcode(["ltvm"], shell=shell)
    if shell != "zsh":
        return code
    # See the module docstring: an autoloaded _ltvm must complete on the
    # call that loaded it, not merely install a function for next time.
    return (
        "#compdef ltvm\n"
        "# Generated by `ltvm completion --shell zsh`.\n"
        f"{code}\n"
        '_python_argcomplete "$@"\n'
    )


def detect_shell(env: dict[str, str] | None = None) -> str:
    """Guess the caller's shell from ``$SHELL``, defaulting to bash.

    ``$SHELL`` is the login shell, not necessarily the running one, but
    it is the only signal available to a process the shell forked --
    and being wrong only means the user passes ``--shell``.
    """
    environ = os.environ if env is None else env
    name = Path(environ.get("SHELL", "")).name
    # Strip a version suffix some distros use (bash5, zsh-5.9).
    for shell in SHELLS:
        if name == shell or name.startswith(shell):
            return shell
    return "bash"


@dataclass
class Target:
    """Where one shell's completion file goes."""

    shell: str
    directory: Path
    # False when the directory does not exist yet and would have to be
    # created.  Creating one for a shell nobody has installed would be
    # litter, so callers check `shell_present` first.
    directory_exists: bool

    @property
    def path(self) -> Path:
        return self.directory / _FILENAME[self.shell]


def _base(root: Path | None) -> Path:
    """The prefix every system path is resolved under."""
    if root is not None:
        return Path(root)
    return Path(os.environ.get(_ROOT_ENV) or "/")


def resolve_target(shell: str, root: Path | None = None) -> Target:
    """Pick the install location for *shell* under *root* (default /).

    An explicit *root* beats $LTVM_COMPLETION_ROOT, which beats /.
    """
    base = _base(root)
    candidates = [base / d.lstrip("/") for d in _SEARCH[shell]]
    for cand in candidates:
        if cand.is_dir():
            return Target(shell, cand, True)
    return Target(shell, candidates[-1], False)


def shell_present(shell: str, root: Path | None = None) -> bool:
    """True when this host looks like it has *shell* to complete for.

    Either signal is enough.  An existing completion directory counts
    without the binary on PATH, because an image that ships zsh
    completions but not zsh is still somewhere they belong; and the
    binary counts without the directory, because a freshly installed
    zsh has nothing under /usr/local yet.
    """
    if resolve_target(shell, root).directory_exists:
        return True
    return shutil.which(shell) is not None


@dataclass
class Result:
    shell: str
    path: Path
    # One of: "installed", "unchanged", "skipped", "failed".
    status: str
    detail: str = ""


def install(
    shells: tuple[str, ...] | None = None,
    root: Path | None = None,
    *,
    all_shells: bool = False,
) -> list[Result]:
    """Write the completion file for each requested shell.

    By default installs for every shell this host appears to have.
    ``all_shells`` installs for all three regardless, creating the
    directories -- for building an image that will be used elsewhere.

    Never raises: a shell we cannot write to is reported, not fatal.
    Tab completion is a convenience, and failing `ltvm install` over it
    would be out of proportion.
    """
    out: list[Result] = []
    for shell in shells or SHELLS:
        target = resolve_target(shell, root)
        if not all_shells and not shell_present(shell, root):
            out.append(
                Result(shell, target.path, "skipped", f"no {shell} on host")
            )
            continue
        try:
            code = shellcode(shell)
        except (ImportError, ValueError) as e:
            out.append(Result(shell, target.path, "failed", str(e)))
            continue
        try:
            if target.path.exists() and target.path.read_text() == code:
                out.append(Result(shell, target.path, "unchanged"))
                continue
        except OSError:
            # Unreadable but present: fall through and try to replace it.
            pass
        try:
            # atomic_write elevates only the write itself when the
            # directory is not user-writable, which is what lets
            # `ltvm doctor --fix` and `ltvm completion --install` work
            # without the whole command running as root.  It also
            # leaves a system file's ownership alone, so the completion
            # file stays root-owned rather than becoming the invoking
            # user's to rewrite at will.
            from .priv import atomic_write

            atomic_write(target.path, code, 0o644)
        except (OSError, RuntimeError) as e:
            out.append(Result(shell, target.path, "failed", str(e)))
            continue
        out.append(Result(shell, target.path, "installed"))
    return out


def uninstall(
    shells: tuple[str, ...] | None = None, root: Path | None = None
) -> list[Result]:
    """Remove the completion file for each shell, wherever it landed.

    Walks every candidate directory rather than just the preferred one:
    an earlier install may have picked a different path, or the
    directory that existed then may not be the one that exists now.
    """
    out: list[Result] = []
    base = _base(root)
    for shell in shells or SHELLS:
        for d in _SEARCH[shell]:
            path = base / d.lstrip("/") / _FILENAME[shell]
            if not path.exists():
                continue
            try:
                path.unlink()
            except PermissionError:
                # Same story as install: elevate the one operation that
                # needs it rather than the whole command.
                from .priv import sudo_run

                try:
                    sudo_run(["rm", "-f", str(path)], quiet=True)
                except Exception as e:  # noqa: BLE001
                    out.append(Result(shell, path, "failed", str(e)))
                    continue
            except OSError as e:
                out.append(Result(shell, path, "failed", str(e)))
                continue
            out.append(Result(shell, path, "removed"))
    return out


def status(root: Path | None = None) -> list[Result]:
    """Report, per shell, whether the installed file is current.

    Only shells this host has are reported; a missing fish completion
    on a host without fish is not a problem to fix.  Statuses:
    "current", "stale", "missing", "failed".
    """
    out: list[Result] = []
    for shell in SHELLS:
        if not shell_present(shell, root):
            continue
        target = resolve_target(shell, root)
        try:
            code = shellcode(shell)
        except (ImportError, ValueError) as e:
            out.append(Result(shell, target.path, "failed", str(e)))
            continue
        # An install may have landed in a non-preferred directory.
        base = _base(root)
        found: Path | None = None
        for d in _SEARCH[shell]:
            cand = base / d.lstrip("/") / _FILENAME[shell]
            if cand.exists():
                found = cand
                break
        if found is None:
            out.append(Result(shell, target.path, "missing"))
            continue
        try:
            current = found.read_text() == code
        except OSError as e:
            out.append(Result(shell, found, "failed", str(e)))
            continue
        out.append(Result(shell, found, "current" if current else "stale"))
    return out
