"""Multi-node cluster management commands."""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from .qemu_run import die, is_running, kill_qemu, run
from .vm_net import SSH_OPTS, run_ssh, sshpass_ssh_argv, unregister_ssh_name
from .vm_owner import resolve_owner_id
from .vm_state import (
    DEFAULT_TARGET,
    EXIT_TIMEOUT,
    ROOT_PASSWORD,
    SOCKETS,
    ClusterInfo,
    ClusterNode,
    ClusterNotFound,
    VMInfo,
    VMNotFound,
    lustre_libdir,
)


def _sudo_prefix() -> list[str]:
    """``["sudo"]`` unless we are already root, mirroring priv.sudo_run().

    Used for the per-node ``ltvm create`` / ``ltvm destroy`` children so
    they inherit the outer SUDO_USER rather than having a nested sudo
    overwrite it with "root".
    """
    return [] if os.geteuid() == 0 else ["sudo"]


def parse_node_spec(spec: str) -> ClusterNode:
    """Parse a node spec like 'mgs+mds:myvm:1' or 'oss:myoss:3'.

    Format: roles:vmname[:diskcount]
    """
    parts = spec.split(":")
    if len(parts) < 2:
        die(f"invalid node spec '{spec}': need roles:name[:disks]")

    roles_str = parts[0]
    name = parts[1]
    # Validate the node name shares the same restrictions cmd_create
    # enforces -- spaces or special chars would break /etc/hosts /
    # SSH config / hostname / fc_name= cmdline.
    from .vm_commands import _validate_vm_name

    _validate_vm_name(name)
    if len(parts) > 2:
        try:
            disk_count = int(parts[2])
        except ValueError:
            die(
                f"invalid disk count '{parts[2]}' in spec '{spec}': "
                f"must be a non-negative integer (format: roles:name[:disks])"
            )
    else:
        disk_count = 0

    roles = roles_str.lower().split("+")
    for r in roles:
        if r not in ("mgs", "mds", "oss", "client"):
            die(f"unknown role '{r}' in spec '{spec}'")

    mdt_disks = 0
    ost_disks = 0
    if "mds" in roles:
        mdt_disks = max(disk_count, 1)
    if "oss" in roles:
        ost_disks = max(disk_count, 1)

    return ClusterNode(
        name=name,
        roles=roles,
        mdt_disks=mdt_disks,
        ost_disks=ost_disks,
    )


def generate_local_sh(
    cluster: ClusterInfo,
    os_family: str = "rhel",
    fstype: str = "ldiskfs",
) -> str:
    """Generate cfg/local.sh content for a multi-node cluster.

    ``fstype`` selects the OSD backend.  Only this line changes for
    ZFS: the MDSDEV*/OSTDEV* written above are the *vdevs* ZFS builds
    its pools on (test-framework.sh's mdsvdevname/ostvdevname), and the
    dataset names default to ``$FSNAME-mdt<n>/mdt<n>``.
    """
    if fstype not in ("ldiskfs", "zfs"):
        raise ValueError(f"unsupported fstype: {fstype!r}")
    mgs = cluster.mgs_node()
    mds_list = cluster.mds_nodes()
    oss_list = cluster.oss_nodes()
    client_list = cluster.client_nodes()

    lustre_dir = lustre_libdir(os_family)
    lines = [
        f"# Cluster: {cluster.name}",
        "# Generated by ltvm cluster deploy",
        "",
        "FSNAME=lustre",
        "NETTYPE=tcp",
        "",
        f"LUSTRE={lustre_dir}",
        f"RLUSTRE={lustre_dir}",
        f"RPWD={lustre_dir}/tests",
        "",
    ]

    lines.append(f"mgs_HOST={mgs.name}")
    lines.append(f"MGSNID={mgs.ip}@tcp")

    combined = mgs.is_mds
    if not combined:
        lines.append("MGSDEV=/dev/vdb")
    lines.append("")

    if mds_list:
        lines.append(f"mds_HOST={mds_list[0].name}")
        total_mdts = sum(n.mdt_disks for n in mds_list)
        lines.append(f"MDSCOUNT={total_mdts}")

        mdt_idx = 1
        for mds_node in mds_list:
            # MDS disks always start at /dev/vdb on the MDS node.  If
            # MGS+MDS share a node (`combined`), no separate MGS disk
            # exists.  If they don't share, the MGS disk lives on the
            # MGS node, not on this MDS node, so no offset is needed
            # here either.
            disk_offset = 1

            for d in range(mds_node.mdt_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"MDSDEV{mdt_idx}=/dev/vd{letter}")
                if len(mds_list) > 1:
                    lines.append(
                        f"mds{mdt_idx}_HOST={mds_node.name}",
                    )
                mdt_idx += 1
        lines.append("")

    if oss_list:
        lines.append(f"ost_HOST={oss_list[0].name}")
        total_osts = sum(n.ost_disks for n in oss_list)
        lines.append(f"OSTCOUNT={total_osts}")

        ost_idx = 1
        for oss_node in oss_list:
            disk_offset = 1
            if oss_node.is_mgs and not oss_node.is_mds:
                disk_offset = 2
            if oss_node.is_mds:
                # If this OSS node is also the MDS, OST disks come
                # after the MDT disks.  Note: an OSS+MDS+MGS node has
                # `combined=True` (mgs.is_mds is True for it), so the
                # extra-MGS-disk offset only applies in the standalone
                # MGS case which lives on a different node entirely.
                disk_offset = 1 + oss_node.mdt_disks

            for d in range(oss_node.ost_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"OSTDEV{ost_idx}=/dev/vd{letter}")
                if len(oss_list) > 1:
                    lines.append(
                        f"ost{ost_idx}_HOST={oss_node.name}",
                    )
                ost_idx += 1
        lines.append("")

    if client_list:
        client_names = ",".join(n.name for n in client_list)
        lines.append(f"CLIENTS={client_names}")
        # RCLIENTS is the variable the test framework actually reads.
        #
        # init_clients_lists() (test-framework.sh, called unconditionally
        # from init_logging()) rebuilds CLIENTS *from* RCLIENTS:
        #
        #     clients="$SINGLECLIENT $HOSTNAME $RCLIENTS"
        #     export CLIENTS=$(comma_list $clients)
        #
        # so a CLIENTS= set here and nothing else is overwritten with
        # just the local node, and every remote client silently drops
        # out.  Multi-client suites (sanityn, parallel-scale,
        # recovery-*-scale) then run green against one client while
        # appearing to have used the whole cluster.
        #
        # Tests are driven from the first client, which is the node
        # init_clients_lists() treats as local, so the remote set is
        # clients[1:].  Space-separated to match what hostlist_expand()
        # and the rest of the framework expect.
        rclients = [n.name for n in client_list[1:]]
        if rclients:
            lines.append('RCLIENTS="{}"'.format(" ".join(rclients)))
    lines.append("")

    lines.append(f"FSTYPE={fstype}")
    lines.append("OSTSEQWIDTH=${OSTSEQWIDTH:-0x20000}")
    lines.append("")

    lines.append("LCTL=/usr/sbin/lctl")
    lines.append("LFS=/usr/bin/lfs")
    lines.append("")

    lines.append('PDSH="pdsh -S -Rssh -w"')
    lines.append("LOAD_MODULES_REMOTE=true")
    lines.append("MOUNT=/mnt/lustre")
    lines.append("MOUNT1=${MOUNT1:-$MOUNT}")
    lines.append("MOUNT2=/mnt/lustre2")
    lines.append("MOUNT3=${MOUNT3:-${MOUNT}3}")
    lines.append("DIR=${DIR:-$MOUNT}")
    lines.append("DIR1=${DIR1:-$MOUNT1}")
    lines.append("DIR2=${DIR2:-$MOUNT2}")
    lines.append("DIR3=${DIR3:-$MOUNT3}")
    lines.append("")

    # This file *replaces* Lustre's own cfg/local.sh, so anything the
    # stock file defines and the framework then reads has to be
    # restated here.  RUNAS_ID/RUNAS_GID/RUNAS are the ones that bite:
    # sanity.sh calls check_runas_id() during setup, which dies with
    # "check_runas_id_ret requires myRUNAS argument" when RUNAS is
    # empty -- so every suite aborts before its first test.  Values and
    # the non-root branch mirror lustre/tests/cfg/local.sh; uid 500 is
    # the `runas` user baked into the ltvm images.
    lines.append("if [ $UID -ne 0 ]; then")
    lines.append('\tRUNAS_ID="$UID"')
    lines.append("\tRUNAS_GID=$(id -g $USER)")
    lines.append('\tRUNAS=""')
    lines.append("else")
    lines.append("\tRUNAS_ID=${RUNAS_ID:-500}")
    lines.append("\tRUNAS_GID=${RUNAS_GID:-$RUNAS_ID}")
    lines.append('\tRUNAS=${RUNAS:-"runas -u $RUNAS_ID -g $RUNAS_GID"}')
    lines.append("fi")
    lines.append("")

    return "\n".join(lines) + "\n"


# ── cluster commands ─────────────────────────────────────


def _create_one_node(
    node: ClusterNode,
    vcpus: int,
    mem: int | None,
    os_target: str | None = None,
    arch: str | None = None,
    disk_size: str | None = None,
    nics: list[str] | None = None,
    owner_id: str | None = None,
) -> tuple[str, int, str]:
    """Create a single cluster VM via ltvm subprocess.

    Returns (node_name, returncode, combined_output).
    Running via subprocess avoids threading issues with shared print/state
    inside cmd_create, and lets all nodes boot concurrently.

    `mem=None` means "let the inner cmd_create resolve from the target's
    default_mem", so cluster nodes inherit the per-target memory default
    instead of being silently overridden by a hardcoded constant in the
    cluster CLI parser.

    `nics` is an optional list of `--nic` spec strings that get applied
    uniformly to every node.  Validation of each spec (including the
    reserved-type rejection for softroce/passthrough) happens inside
    the child `ltvm create`, so bad specs surface per-node with the
    follow-up-issue hint the single-node path prints.
    """
    mgs_disk = 1 if (node.is_mgs and not node.is_mds) else 0
    # No `sudo` prefix when already root: cluster create requires root, so
    # a nested sudo would reset SUDO_USER to "root" in the child and the
    # child's ~/.ssh bookkeeping would target root's home instead of the
    # invoking user's.  (On macOS that is a hard failure -- root's home is
    # /var/root and /root is on the read-only system volume.)
    cmd = _sudo_prefix() + [
        "ltvm",
        "create",
        node.name,
        "--vcpus",
        str(vcpus),
    ]
    if mem is not None:
        cmd += ["--mem", str(mem)]
    if os_target:
        cmd += ["--target", os_target]
    if arch:
        cmd += ["--arch", arch]
    if disk_size:
        cmd += ["--disk-size", disk_size]
    if owner_id:
        # Pass the cluster parent's resolved value explicitly so all members
        # share one owner even though each child has a different process PID.
        cmd += ["--owner-id", owner_id]
    # Always pass both counts, including zero.  Omitting a flag lets
    # `ltvm create`'s defaults (1 MDT, 2 OST) apply, so an oss-only
    # node silently gained an MDT-slot disk ahead of its OSTs -- which
    # shifts every /dev/vd* letter past what generate_local_sh computes
    # (its disk_offset assumes exactly the disks the role asked for).
    # The result mounted fine, because the backing files are
    # identical-size scratch images, while OSTDEV1 pointed at the
    # spurious disk and the last real OST disk went unused.
    cmd += ["--mdt-disks", str(node.mdt_disks + mgs_disk)]
    cmd += ["--ost-disks", str(node.ost_disks)]
    for nic in nics or []:
        cmd += ["--nic", nic]

    # 300s: cold boot + disk creation + first-boot SSH wait (the inner
    # `ltvm create` already enforces SSH_TIMEOUT, but we leave headroom
    # for slow hosts and large disk allocations).
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    except subprocess.TimeoutExpired as e:
        # See _write_cluster_local_sh: don't propagate out of the parallel
        # executor; report the failure via the (name, rc, output) tuple
        # so the cluster create driver can summarise per-node failures.
        return node.name, 1, f"create timed out after {e.timeout}s"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node.name, r.returncode, combined.rstrip("\n")


def _print_cluster_plan(
    cluster_name: str,
    node_specs: list[ClusterNode],
    *,
    vcpus: int,
    mem: int | None,
    os_target: str | None,
    arch: str | None,
    disk_size: str | None,
    nics: list[str],
    owner_id: str | None,
) -> None:
    """Report what `cluster create` would do, for --dry-run.

    Per-node IPs are not shown: each node's `ltvm create` claims one
    under a lock, so there is no honest answer without claiming them.
    """
    print(
        f"Would create cluster '{cluster_name}' with {len(node_specs)} nodes:"
    )
    for node in node_specs:
        disks = []
        if node.mdt_disks:
            disks.append(f"{node.mdt_disks} MDT")
        if node.ost_disks:
            disks.append(f"{node.ost_disks} OST")
        print(
            f"  {node.name:<20} roles={'+'.join(node.roles):<16} "
            f"disks={', '.join(disks) or 'none'}"
        )
    mem_desc = f"{mem} MB" if mem is not None else "target default"
    arch_desc = f" arch={arch}" if arch else ""
    print("Applied to every node:")
    print(f"  target:  {os_target or 'default'}{arch_desc}")
    print(f"  cpu/mem: {vcpus} vcpus, {mem_desc}")
    if disk_size:
        print(f"  disk:    {disk_size} each")
    if nics:
        print(f"  nics:    eth0 (mgmt) + {', '.join(nics)}")
    print(f"  owner:   {owner_id}")
    print("Nothing was written.  Re-run without --dry-run to create it.")


def cmd_cluster_create(args: argparse.Namespace) -> None:
    cluster_name = args.name
    # Cluster name flows into filesystem paths (SOCKETS/<name>.cluster)
    # so it needs the same character whitelist as VM names.
    from .vm_commands import _validate_vm_name

    _validate_vm_name(cluster_name)
    if (SOCKETS / f"{cluster_name}.cluster").exists():
        die(f"cluster '{cluster_name}' already exists")

    node_specs = [parse_node_spec(s) for s in args.nodes]

    # Refuse a spec that names the same node twice.  Nothing checked,
    # so `cluster create co2 mgs+mds:co2-a:1 oss:co2-a:3` launched two
    # concurrent `ltvm create co2-a` subprocesses racing on one .info,
    # overlay and TAP -- or the loser adopted the winner and reported
    # success.  The saved ClusterInfo then carried the same host twice
    # with contradictory disk roles, and generate_local_sh assigned it
    # MDSDEV and OSTDEV letters from two different disk_offset
    # computations, pointing at overlapping devices.
    seen_names: set[str] = set()
    dupes: set[str] = set()
    for n in node_specs:
        if n.name in seen_names:
            dupes.add(n.name)
        seen_names.add(n.name)
    if dupes:
        die(
            f"node name(s) listed more than once: "
            f"{', '.join(sorted(dupes))}\n"
            f"Each node in a cluster needs its own name."
        )

    # Refuse to build a cluster on top of VMs that already exist.
    # `ltvm create` is idempotent -- _handle_existing_vm starts a
    # stopped VM and exits 0 -- so without this check the cluster
    # silently adopts them.  That matters because the failure path
    # below destroys every name in node_specs: one node failing to
    # come up would delete a pre-existing VM (overlay and data disks
    # included) that this command never created.  `cluster destroy`
    # would do the same later.  Adopting is also wrong on its own
    # terms, since an existing VM won't have the disk layout the role
    # implies.
    taken = [
        n.name for n in node_specs if (SOCKETS / f"{n.name}.info").exists()
    ]
    if taken:
        die(
            f"VM(s) already exist: {', '.join(taken)}\n"
            f"cluster create would adopt them, and would destroy them "
            f"if another node failed.\n"
            f"Destroy them first, or pick different node names."
        )

    mgs_count = sum(1 for n in node_specs if n.is_mgs)
    if mgs_count == 0:
        die("cluster needs at least one node with mgs role")
    if mgs_count > 1:
        die("cluster can only have one MGS node")

    if not any(n.is_mds for n in node_specs):
        die("cluster needs at least one node with mds role")

    vcpus = args.vcpus
    mem = args.mem
    os_target = getattr(args, "os", None)
    arch = getattr(args, "arch", None)
    disk_size = getattr(args, "disk_size", None)
    # Multi-NIC: same list of --nic specs applies to every node in the
    # cluster.  The CLI layer (cli.py::cmd_cluster) collects them into
    # args.nic; older call sites that don't know about --nic land here
    # with the attr unset, in which case we pass an empty list through.
    nics: list[str] = list(getattr(args, "nic", None) or [])
    try:
        owner_id = resolve_owner_id(getattr(args, "owner_id", None))
    except ValueError as e:
        die(str(e))

    if getattr(args, "dry_run", False):
        # Everything above is validation and reads -- name rules,
        # duplicate node names, already-taken VMs, the mgs/mds role
        # rules, owner resolution.  The first thing written is a node,
        # created by the pool below.
        _print_cluster_plan(
            cluster_name,
            node_specs,
            vcpus=vcpus,
            mem=mem,
            os_target=os_target,
            arch=arch,
            disk_size=disk_size,
            nics=nics,
            owner_id=owner_id,
        )
        return

    print(f"=== Creating cluster '{cluster_name}' ===")
    if os_target:
        print(f"    Target: {os_target}{(' arch=' + arch) if arch else ''}")
    print(f"    Creating {len(node_specs)} nodes in parallel...")

    failed = []
    with ThreadPoolExecutor(max_workers=len(node_specs)) as executor:
        futures = {
            executor.submit(
                _create_one_node,
                node,
                vcpus,
                mem,
                os_target,
                arch,
                disk_size,
                nics,
                owner_id,
            ): node
            for node in node_specs
        }
        for future in as_completed(futures):
            node = futures[future]
            try:
                name, rc, output = future.result()
            except Exception as e:
                # Don't let one node's exception (e.g. TimeoutExpired
                # from the inner subprocess) abandon the remaining
                # futures.  Mark this one as failed and keep
                # collecting -- the cleanup loop below needs an
                # accurate `failed` list.
                name = node.name
                rc = -1
                output = f"exception: {type(e).__name__}: {e}"
            if rc != 0:
                print(f"\n--- {name}: FAILED (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: up")

    if failed:
        # Clean up ALL nodes, including the failed ones.  A failed
        # `ltvm create` may have already created the TAP, overlay,
        # and .info file before erroring out (e.g. SSH wait timed out
        # so the rollback in cmd_create couldn't run).  `ltvm destroy`
        # is idempotent on missing VMs, so it's safe to call on every
        # node and necessary to avoid leaking partial state.
        for node in node_specs:
            r = subprocess.run(
                _sudo_prefix() + ["ltvm", "destroy", node.name],
                capture_output=True,
            )
            if r.returncode != 0:
                print(
                    f"warning: failed to destroy VM '{node.name}' during cleanup",
                    file=sys.stderr,
                )
        die(f"vm create failed for: {', '.join(failed)}")

    # Load IPs now that all VMs are running
    for node in node_specs:
        vm = VMInfo.load(node.name)
        node.ip = vm.ip

    cluster = ClusterInfo(
        name=cluster_name,
        owner_id=owner_id,
        nodes=[
            {
                "name": n.name,
                "roles": n.roles,
                "mdt_disks": n.mdt_disks,
                "ost_disks": n.ost_disks,
                "ip": n.ip,
            }
            for n in node_specs
        ],
    )
    cluster.save()

    print(f"\n=== Cluster '{cluster_name}' created ===")
    print(f"  owner: {owner_id}")
    for n in node_specs:
        print(f"  {n.name:<20} {n.ip:<18} {'+'.join(n.roles)}")
    print(
        f"\nNext: ltvm cluster deploy {cluster_name} "
        f"--build /path/to/lustre-release [--mount]"
    )


def _deploy_one_node(
    node_name: str,
    lustre_tree: str | Path,
    os_family: str = "rhel",
    zfs_staging: Path | None = None,
) -> tuple[str, int, str]:
    """Deploy Lustre to one cluster node.

    Returns (node_name, returncode, output_message).

    `lustre_tree` is the source tree the cluster's `--build` was
    pointed at; it determines where the per-tree staging dir lives.
    """
    from ltvm_pkg.deploy import deploy_to_vm
    from ltvm_pkg.lustre_build import staging_path as _staging_path

    vm = VMInfo.load(node_name)
    if not vm.os_id:
        raise RuntimeError(f"VM '{vm.name}' has no os_id; recreate it")
    target = vm.os_id
    # Pass vm.arch + kernel so the staging dir matches what
    # build-lustre wrote.  Staging is keyed per-kernel so two kernels'
    # userland can coexist under one lustre tree.
    vm_arch = vm.arch
    deploy_kernel: str | None = None
    if vm.kernel:
        vm_kernel_name = Path(vm.kernel).parent.name
        if vm_kernel_name:
            deploy_kernel = vm_kernel_name
    if deploy_kernel is None:
        return (
            node_name,
            1,
            f"cannot resolve kernel for {node_name}: vm.kernel is unset",
        )
    staging = _staging_path(
        lustre_tree,
        target,
        arch=vm_arch,
        kernel=deploy_kernel,
        variant=vm.variant,
    )
    try:
        # No fstype here: the cluster's cfg/local.sh is written whole
        # further down (generate_local_sh), so a per-node FSTYPE block
        # would be overwritten moments later.
        deploy_to_vm(vm, staging, os_family=os_family, zfs_staging=zfs_staging)
        return node_name, 0, "ok"
    except RuntimeError as e:
        return node_name, 1, str(e)


def _write_cluster_local_sh(
    node_name: str,
    node_ip: str,
    local_sh: str,
    ssh_opts: list[str],
    os_family: str = "rhel",
) -> tuple[str, int, str]:
    """Write cluster local.sh to the standard test location on a node.

    Returns (node_name, returncode, output).
    """
    lustre_dir = lustre_libdir(os_family)
    cfg_path = f"{lustre_dir}/tests/cfg/local.sh"
    try:
        r = subprocess.run(
            sshpass_ssh_argv(
                node_ip,
                f"mkdir -p {lustre_dir}/tests/cfg && cat > {cfg_path}",
            ),
            input=local_sh,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except subprocess.TimeoutExpired as e:
        # Don't propagate out of the parallel executor; the caller checks
        # the returncode field and reports per-node failures.  Without
        # this catch, one stalled node tracebacks out of future.result()
        # and aborts the cluster config rollout mid-flight.
        return node_name, 1, f"timed out after {e.timeout}s writing {cfg_path}"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node_name, r.returncode, combined.rstrip("\n")


def _parallel_cluster_op(
    nodes: list,
    submit: Any,
    success_verb: str,
    failure_verb: str,
) -> list[str]:
    """Fan out ``submit(node)`` across a thread pool and collect results.

    Each submitted future must return a ``(name, rc, output)`` tuple.
    Prints per-node progress and returns the list of failed node names
    so the caller can decide whether to die() or continue.
    """
    failed: list[str] = []
    with ThreadPoolExecutor(max_workers=len(nodes)) as executor:
        futures = {executor.submit(submit, node): node for node in nodes}
        for future in as_completed(futures):
            node = futures[future]
            try:
                name, rc, output = future.result()
            except Exception as e:
                # _deploy_one_node can raise past its own except
                # RuntimeError -- VMInfo.load raises VMNotFound, which
                # is not a RuntimeError -- and an unguarded result()
                # aborted the whole fan-out with a Python traceback:
                # no per-node report, no "deploy failed for: ...",
                # update_deploy never recorded, local.sh never
                # distributed.  cmd_cluster_create already wraps its
                # result() for exactly this reason.
                name = getattr(node, "name", str(node))
                print(f"\n--- {name}: {failure_verb} ---\n{e}")
                failed.append(name)
                continue
            if rc != 0:
                print(f"\n--- {name}: {failure_verb} (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: {success_verb}")
    return failed


def _validate_lustre_source(path: Path) -> None:
    """Die with a clear message if path is not a Lustre source tree.

    Only checks that the directory looks like a Lustre tree.
    Cluster deploy runs `ltvm build lustre` itself, so a freshly
    cloned tree (no .ko files yet) is valid input.
    """
    if not path.is_dir():
        die(f"--build:'{path}' is not a directory")

    missing = [
        name
        for name in ("configure.ac", "lustre", "lnet")
        if not (path / name).exists()
    ]
    if missing:
        die(
            f"--build:'{path}' does not look like a Lustre "
            f"source tree (missing: {', '.join(missing)})"
        )


def cmd_cluster_deploy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()
    src = Path(args.lustre_source).expanduser().resolve()
    _validate_lustre_source(src)
    build = str(src)

    # --server-only only affects the llmount.sh invocation, which only
    # runs when --mount is set.  Reject the combination instead of
    # silently dropping the flag.
    if getattr(args, "server_only", False) and not getattr(
        args, "mount", False
    ):
        die("--server-only requires --mount")

    # Derive os_family and target+kernel+arch from the first node's
    # metadata (all nodes in a cluster share the same target).  We also
    # pull the kernel name and arch off the VM so build-lustre uses the
    # right kernel tree and arch -- not just the target's defaults.
    os_family = "rhel"
    target = DEFAULT_TARGET
    kernel_name: str | None = None
    arch: str = "x86_64"
    try:
        first_vm = VMInfo.load(nodes[0].name)
    except (VMNotFound, IndexError) as e:
        die(f"cluster {cluster.name!r}: cannot load first node: {e}")
    if first_vm.os_id:
        from .target_config import TargetConfig

        target = first_vm.os_id
        # Let ValueError from TargetConfig propagate up with a clear
        # error.  Previously a broad `except (..., ValueError, ...): pass`
        # silently fell back to DEFAULT_TARGET, which deployed rocky9 .ko
        # files onto whatever the cluster actually ran.
        try:
            os_family = TargetConfig(
                target, arch=first_vm.arch or None
            ).os_family
        except ValueError as e:
            die(f"cluster {cluster.name!r}: target {target!r}: {e}")
    if first_vm.kernel:
        # vm.kernel points at .../kernels/<name>/vmlinuz; extract <name>
        kernel_name = Path(first_vm.kernel).parent.name
    if first_vm.arch:
        arch = first_vm.arch

    print(f"=== Deploying to cluster '{cluster.name}' ===")
    print(f"    Build: {build}")

    # Build Lustre from source before deploying.  All nodes share the
    # same target+kernel+arch, so we run build-lustre once and every
    # node rsyncs from the same staging dir.
    # --zfs-version implies --zfs; --fstype zfs implies both, since
    # the cluster cannot mount a ZFS target without ZFS on its nodes.
    # And --zfs on a deploy means "run on ZFS" unless --fstype says
    # otherwise -- same rule as single-node deploy-lustre.
    fstype = getattr(args, "fstype", None)
    zfs_version_arg = getattr(args, "zfs_version", None)
    want_zfs = (
        bool(getattr(args, "zfs", False))
        or bool(zfs_version_arg)
        or fstype == "zfs"
    )
    if want_zfs and fstype is None:
        fstype = "zfs"
    if fstype is None:
        fstype = "ldiskfs"

    build_cmd = ["ltvm", "build", "lustre", target, "--lustre-tree", build]
    if kernel_name:
        build_cmd += ["--kernel", kernel_name]
    # Forward --arch unconditionally.  Comparing against the literal
    # "x86_64" is wrong for a target whose default arch is something
    # else -- see the matching cmd_deploy comment.
    build_cmd += ["--arch", arch]
    if getattr(args, "force_compat", False):
        build_cmd += ["--force-compat"]
    if want_zfs:
        build_cmd += ["--zfs"]
        if zfs_version_arg:
            build_cmd += ["--zfs-version", zfs_version_arg]
    sudo_user = os.environ.get("SUDO_USER")
    if sudo_user:
        build_cmd = ["sudo", "-u", sudo_user] + build_cmd
    print(f"--- Building Lustre against {target} kernel tree...")
    rb = subprocess.run(build_cmd)
    if rb.returncode != 0:
        die(f"Lustre build failed (rc={rb.returncode})")

    # Which ZFS to ship is the staged build's decision (osd_zfs.ko is
    # linked against one specific build), and every node in a cluster
    # shares one target+kernel+arch -- so resolve it once here rather
    # than per node.
    zfs_staging: Path | None = None
    if want_zfs:
        from .lustre_build import read_staging_meta
        from .lustre_build import staging_path as _staging_path
        from .target_config import TargetConfig
        from .zfs_build import zfs_staging_dir

        tc = TargetConfig(target, arch=arch, variant=first_vm.variant)
        meta = read_staging_meta(
            _staging_path(
                build,
                target,
                arch=arch,
                kernel=kernel_name or tc.default_kernel,
                variant=first_vm.variant,
            )
        )
        staged_zfs = meta.get("zfs_version") if isinstance(meta, dict) else None
        if not staged_zfs:
            die(
                "ZFS was requested but the Lustre build produced no ZFS "
                "record -- rerun with --force to reconfigure"
            )
        zfs_staging = zfs_staging_dir(tc, kernel_name, staged_zfs)
        if not any((zfs_staging / "lib" / "modules").rglob("zfs.ko*")):
            die(
                f"Lustre was built against ZFS {staged_zfs} but its "
                f"build artifact is missing from {zfs_staging}"
            )
        print(f"    ZFS: {staged_zfs}")

    print(f"    Deploying to {len(nodes)} nodes in parallel...")

    # Deploy to all nodes in parallel -- same as single-node deploy,
    # just run concurrently.
    failed = _parallel_cluster_op(
        nodes,
        lambda node: _deploy_one_node(node.name, build, os_family, zfs_staging),
        success_verb="deployed",
        failure_verb="FAILED",
    )

    if failed:
        die(f"deploy failed for: {', '.join(failed)}")

    # Record successful deploys on each VMInfo so `ltvm list` shows
    # last_deploy/build_path/kver -- single-node cmd_deploy does this
    # at the end of its flow; cluster deploy was missing it.
    import time as _time

    _now = int(_time.time())
    unrecorded: list[str] = []
    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            vm.update_deploy(_now, build, vm.kver)
        except VMNotFound:
            pass
        except PermissionError:
            # Same as single-node deploy: cluster deploy is unprivileged
            # and update_deploy never prompts, so a root-owned sockets/
            # without cached sudo costs only the bookkeeping.
            unrecorded.append(node.name)
    if unrecorded:
        print(
            f"  Warning: deploy metadata not recorded for "
            f"{', '.join(unrecorded)} (sockets dir is root-owned and "
            f"sudo needs a password); the deploy itself succeeded.",
            file=sys.stderr,
        )

    # Overwrite single-node local.sh with the cluster topology config.
    local_sh = generate_local_sh(cluster, os_family=os_family, fstype=fstype)
    print("\n--- Distributing cluster config (local.sh)...")
    print(local_sh)

    ssh_opts = SSH_OPTS
    try:
        node_ips = {node.name: VMInfo.load(node.name).ip for node in nodes}
    except VMNotFound as e:
        die(f"cluster node missing: {e}")
    failed_sh = _parallel_cluster_op(
        nodes,
        lambda node: _write_cluster_local_sh(
            node.name,
            node_ips[node.name],
            local_sh,
            ssh_opts,
            os_family,
        ),
        success_verb="local.sh written",
        failure_verb="local.sh FAILED",
    )

    if failed_sh:
        die(f"local.sh distribution failed for: {', '.join(failed_sh)}")

    if args.mount:
        print("=== Mounting Lustre filesystem ===")
        mgs = cluster.mgs_node()
        mgs_vm = VMInfo.load(mgs.name)

        lustre_dir = lustre_libdir(os_family)
        mount_cmd = (
            f"cd {lustre_dir}/tests && LUSTRE={lustre_dir} bash llmount.sh"
        )
        if args.server_only:
            mount_cmd += " --server-only"

        print(f"Running llmount.sh from {mgs.name}...")
        try:
            r = run(
                sshpass_ssh_argv(mgs_vm.ip, mount_cmd),
                capture_output=False,
                timeout=300,
            )
        except subprocess.TimeoutExpired as e:
            die(
                f"llmount.sh timed out after {e.timeout}s on {mgs.name}\n"
                f"  modules are deployed; check `ssh {mgs.name} dmesg` and "
                f"`ltvm cluster exec {cluster.name} mds 'lctl dl'`"
            )
        if r.returncode != 0:
            die("llmount.sh failed")
        print("=== Lustre mounted ===")

    print(f"\n=== Cluster '{cluster.name}' deployed ===")


def cmd_cluster_destroy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()

    # Use the same _destroy_vm_artifacts helper that single-node
    # cmd_destroy uses, so we don't drift from its cleanup list.
    # The previous inlined loop forgot to unlink the per-VM .info.lock
    # file (added in round 15), causing `ltvm doctor` to report orphan
    # info locks for every node after every cluster destroy.
    from .vm_commands import _destroy_vm_artifacts

    print(f"=== Destroying cluster '{cluster.name}' ===")
    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            kill_qemu(vm)
        except VMNotFound:
            pass

        _destroy_vm_artifacts(node.name)
        unregister_ssh_name(node.name)
        print(f"  destroyed {node.name}")

    cluster.path.unlink(missing_ok=True)
    print(f"=== Cluster '{cluster.name}' destroyed ===")


def cmd_cluster_list(args: argparse.Namespace) -> None:
    names = ClusterInfo.all_names()
    if not names:
        print("(no clusters)")
        return
    for cname in names:
        try:
            cluster = ClusterInfo.load(cname)
        except ClusterNotFound:
            # Race: .cluster file disappeared between all_names() and load().
            continue
        except (RuntimeError, ValueError) as e:
            # Corrupt or malformed cluster file -- flag it and keep
            # listing the rest rather than crashing.  Better to see
            # "clusterA: <BROKEN: ...>" than to get nothing at all.
            print(f"{cname}: <BROKEN: {e}>")
            continue
        nodes = cluster.get_nodes()
        node_summary = []
        for n in nodes:
            roles = "+".join(n.roles)
            try:
                running = "up" if is_running(VMInfo.load(n.name)) else "down"
            except VMNotFound:
                running = "missing"
            node_summary.append(f"{n.name}({roles},{running})")
        owner = cluster.owner_id or "-"
        print(f"{cname}: {' '.join(node_summary)} owner={owner}")


def cmd_cluster_status(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()

    print(f"cluster: {cluster.name}")
    print(f"owner:   {cluster.owner_id or '-'}")
    print(f"nodes:   {len(nodes)}")
    print()

    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            running = is_running(vm)
        except VMNotFound:
            running = False

        status = "running" if running else "stopped"
        roles = "+".join(node.roles)
        disks = ""
        if node.mdt_disks:
            disks += f" mdt={node.mdt_disks}"
        if node.ost_disks:
            disks += f" ost={node.ost_disks}"
        if node.is_mgs and not node.is_mds:
            disks += " mgs=1"

        print(
            f"  {node.name:<20} {node.ip:<18} {status:<8} {roles:<12}{disks}",
        )


def cmd_cluster_ssh(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    # ssh opens one interactive session, so a role selects its first
    # node (unlike `cluster exec`, which fans out).  Prefer an exact
    # node-name match so an explicit name is never shadowed by a role.
    exact = [n for n in nodes if n.name == target]
    by_role = [n for n in nodes if target in n.roles]
    candidates = exact or by_role
    matched = candidates[0] if candidates else None
    if matched is None:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )
        raise AssertionError("unreachable")

    vm = VMInfo.load(matched.name)
    ssh_args = [
        "sshpass",
        "-p",
        ROOT_PASSWORD,
        "ssh",
        *SSH_OPTS,
        f"root@{vm.ip}",
        *args.command,
    ]
    os.execvp("sshpass", ssh_args)


def cmd_cluster_exec(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    # A role names every node holding it.  Running on only the first
    # match reported one OSS out of three and exited 0, which reads as
    # "the whole role is healthy" -- and the docs describe this exact
    # command as "run a command on all OSS nodes".  An exact node name
    # still selects exactly that node.
    exact = [n for n in nodes if n.name == target]
    matches = exact or [n for n in nodes if target in n.roles]
    if not matches:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )
        raise AssertionError("unreachable")

    # Two idioms the user might type:
    #   ltvm cluster exec co2 oss 'lctl dl'     -> argv=['lctl dl']
    #   ltvm cluster exec co2 oss lctl dl       -> argv=['lctl', 'dl']
    #
    # shlex.join unconditionally quotes each arg, so the first form
    # becomes "'lctl dl'" -- a single shell token the remote bash
    # reads as a command name containing a space ("lctl dl: command
    # not found", rc=127).  When the argv is already one pre-joined
    # shell string (the user did the quoting), pass it verbatim;
    # otherwise safely quote each argv element so spaces / globs /
    # quotes inside individual args survive transport.
    if len(args.command) == 1:
        command = args.command[0]
    else:
        command = shlex.join(args.command)
    multi = len(matches) > 1
    worst = 0
    for node in matches:
        vm = VMInfo.load(node.name)
        if multi:
            print(f"--- {node.name} ---")
        try:
            r = run_ssh(vm.ip, command, timeout=args.timeout)
        except subprocess.TimeoutExpired:
            if not multi:
                die(f"timeout after {args.timeout}s", EXIT_TIMEOUT)
            print(
                f"{node.name}: timeout after {args.timeout}s",
                file=sys.stderr,
            )
            worst = EXIT_TIMEOUT
            continue
        if r.stdout:
            print(r.stdout, end="")
        if r.stderr:
            print(r.stderr, end="", file=sys.stderr)
        # Exit non-zero if any node did; a role-wide command that
        # failed somewhere must not look like a clean run.
        if r.returncode != 0 and worst == 0:
            worst = r.returncode
    sys.exit(worst)
